name: BetterJL
version: '1.1.0'
main: tr.unknown.betterJL.Main
api-version: '1.16'
authors: [ UnknownDev ]
description: Custom Join and Leave messages for servers.
commands:
  betterjl:
    description: Admin command for reload & help.
    aliases: betterjoinleave